//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GRP2.rc
//
#define ID_Voreinstellungen             3
#define ID_BUTTON_Ax_min                4
#define ID_FXY                          4
#define ID_BUTTON_Ax_0                  5
#define ID_BUTTON_Vx_min                6
#define ID_BUTTON_Ay_0                  7
#define ID_BUTTON_Vx_0                  7
#define ID_BUTTON_Ax_max                8
#define ID_BUTTON_Ay_min                9
#define ID_BUTTON_Ay_max                10
#define ID_BUTTON_Vx_max                11
#define ID_BUTTON_Vy_min                12
#define ID_BUTTON_Vy_max                13
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GRP2_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       130
#define IDR_ACCELERATOR1                134
#define IDD_GRP2_Param_1                139
#define IDD_GRP2_Param_2                140
#define IDD_GRP2_Param_3                141
#define IDD_GRP2_Param_4                142
#define IDD_GRP2_Param_5                143
#define IDD_GRP2_Info                   144
#define IDC_CURSOR1                     147
#define IDC_CURSOR2                     151
#define IDD_GRP2_Diagrm_1               152
#define IDD_GRP2_Diagrm_2               153
#define IDD_GRP2_Diagrm_3               154
#define IDD_GRP2_Fn_1                   155
#define IDD_GRP2_Fn_2                   156
#define IDD_GRP2_Fn_3                   157
#define IDD_GRP2_Prg                    158
#define IDC_CURSOR3                     162
#define IDD_GRP2_Diagrm_4               163
#define IDD_GRP2_Diagrm_5               164
#define IDD_GRP2_koord                  165
#define IDD_GRP2_Diagrm_6               167
#define IDD_GRP2_Fn_4                   168
#define IDD_GRP2_Splash                 169
#define IDB_BITMAP_LOGO                 170
#define IDD_GRP2_Param_2_Bx             171
#define IDD_GRP2_Param_2_By             172
#define IDB_BITMAP_EPSILON              174
#define IDB_BITMAP_S1                   175
#define IDB_BITMAP_S0                   176
#define IDB_BITMAP_pa1                  177
#define IDB_BITMAP_pa2                  178
#define IDB_BITMAP_1                    179
#define IDB_BITMAP_0                    180
#define IDB_BITMAP_crit                 181
#define IDB_BITMAP_SG                   182
#define IDB_BITMAP_AM                   183
#define IDB_BITMAP_SAM                  184
#define IDB_BITMAP_AG3                  185
#define IDB_BITMAP_3                    186
#define IDB_BITMAP_A                    187
#define IDB_BITMAP_4                    188
#define IDB_BITMAP_a3                   189
#define IDB_BITMAP_a4                   190
#define IDB_BITMAP_INTEGRAL             191
#define IDI_ICON_Ax_mx1                 193
#define IDB_BITMAP_INTEGRAL_01          194
#define IDB_BITMAP_DIFF_0               195
#define IDB_BITMAP_DIFF                 196
#define IDB_BITMAP_DIFF_1               197
#define IDB_BITMAP_m1                   198
#define IDB_BITMAP_xy                   199
#define IDB_BITMAP_yx                   200
#define IDB_BITMAP_x                    201
#define IDB_BITMAP_y                    202
#define IDI_ICON_Ax                     203
#define IDI_ICON_Ax_mn1                 204
#define IDI_ICON_Ax_mn0                 205
#define IDI_ICON_Ax_mx0                 207
#define IDD_GRP2_STATUS                 209
#define IDD_GRP2_FXY                    210
#define IDD_GRP2_THETA                  211
#define IDR_MENU2                       213
#define IDD_GRP2_LOG                    214
#define IDC_CHECK_x                     1000
#define IDC_CHECK_y                     1001
#define IDC_CHECK_xm                    1002
#define IDC_CHECK_ym                    1003
#define IDC_CHECK_xA                    1004
#define IDC_CHECK_yA                    1005
#define IDC_CHECK_xV                    1006
#define IDC_CHECK_yV                    1007
#define IDC_CHECK_xS                    1008
#define IDC_CHECK_yS                    1009
#define IDC_CHECK_Fk                    1010
#define IDC_CHECK_xy                    1011
#define IDC_CHECK_xK                    1012
#define IDC_CHECK_yK                    1013
#define IDC_COMBO_emfx                  1014
#define IDC_COMBO_emfy                  1015
#define IDC_EDIT_kjx                    1016
#define IDC_CHECK_x_                    1017
#define IDC_EDIT_kjy                    1018
#define IDC_EDIT_sc                     1019
#define IDC_EDIT_scy                    1020
#define IDC_CHECK_y_                    1021
#define IDC_EDIT_shift_x                1021
#define IDC_CHECK_xSw                   1022
#define IDC_EDIT_shift_x2               1022
#define IDC_BUTTON_scy_dwn              1023
#define IDC_CHECK_xGrd                  1023
#define IDC_EDIT_scy_d                  1024
#define IDC_BUTTON_scy_up               1025
#define IDC_EDIT_shift_y                1025
#define IDC_BUTTON_sc_dwn               1026
#define IDC_EDIT_shift_y2               1026
#define IDC_BUTTON_sc_up                1027
#define IDC_EDIT_sc_d                   1028
#define IDC_EDIT_tlgx                   1029
#define IDC_EDIT_tlgy                   1030
#define IDC_BUTTON_tlgy_dwn             1031
#define IDC_EDIT_tlgy_d                 1032
#define IDC_BUTTON_tlgy_up              1033
#define IDC_BUTTON_tlgx_dwn             1034
#define IDC_BUTTON_tlgx_up              1035
#define IDC_EDIT_tlgx_d                 1036
#define IDC_CHECK_ySw                   1037
#define IDC_CHECK_yGrd                  1038
#define IDC_CHECK_ini                   1071
#define IDC_CHECK1                      1072
#define IDC_CHECK_inv                   1072
#define IDC_CHECK_int                   1072
#define IDC_EDIT_dez_W_x                1073
#define IDC_CHECK4                      1073
#define IDC_CHECK_rnd_dyn               1073
#define IDC_EDIT_dez_W_y                1074
#define IDC_CHECK_syx                   1074
#define IDC_CHECK_rnd_dyn2              1074
#define IDC_CHECK5                      1074
#define IDC_CHECK_s                     1074
#define IDC_EDIT_dez_S_x                1075
#define IDC_CHECK_s1xy                  1075
#define IDC_CHECK7                      1075
#define IDC_CHECK_sg                    1075
#define IDC_EDIT_dez_S_y                1076
#define IDC_CHECK_srxy                  1076
#define IDC_CHECK8                      1076
#define IDC_CHECK_sgx                   1076
#define IDC_EDIT_dez_K_x                1077
#define IDC_CHECK_srx                   1077
#define IDC_CHECK9                      1077
#define IDC_CHECK_a31                   1077
#define IDC_EDIT_dez_K_y                1078
#define IDC_CHECK10                     1078
#define IDC_BUTTON_scy_reset            1079
#define IDC_CHECK11                     1079
#define IDC_CHECK_sa3g                  1079
#define IDC_BUTTON_kjx_dwn              1080
#define IDC_CHECK12                     1080
#define IDC_CHECK_a41                   1080
#define IDC_BUTTON_shift_x_reset        1080
#define IDC_BUTTON_tlgy_reset           1081
#define IDC_CHECK13                     1081
#define IDC_CHECK_ag41                  1081
#define IDC_BUTTON_shift_x_reset2       1081
#define IDC_BUTTON_kjx_up               1082
#define IDC_CHECK14                     1082
#define IDC_CHECK_sa4g                  1082
#define IDC_BUTTON_kjx_reset            1083
#define IDC_EDIT_kjx_d                  1084
#define IDC_BUTTON_Ax_d_reset           1084
#define IDC_BUTTON_kjy_up               1085
#define IDC_BUTTON_Ay_reset             1085
#define IDC_EDIT_kjy_d                  1086
#define IDC_BUTTON_Ay_d_reset           1086
#define IDC_BUTTON_kjy_dwn              1087
#define IDC_BUTTON_Vx_reset             1087
#define IDC_BUTTON_kjy_reset            1088
#define IDC_BUTTON_Vx_d_reset           1088
#define IDC_BUTTON_kjx_d_reset          1089
#define IDC_BUTTON_Vy_reset             1089
#define IDC_BUTTON_kjy_d_reset          1090
#define IDC_BUTTON_Vy_d_reset           1090
#define IDC_BUTTON_sc_reset             1091
#define IDC_BUTTON_sc_d_reset           1092
#define IDC_BUTTON_scy_d_reset          1093
#define IDC_BUTTON_tlgx_reset           1094
#define IDC_BUTTON_shift_y_reset        1094
#define IDC_BUTTON_tlgx_d_reset         1095
#define IDC_BUTTON_shift_y_reset2       1095
#define IDC_BUTTON_tlgy_d_reset         1096
#define IDC_SPIN_dez_W_y                1098
#define IDC_SPIN_dez_S_y                1099
#define IDC_SPIN_dez_K_y                1100
#define IDC_SPIN_tlgx                   1100
#define IDC_SPIN_dez_W_x                1101
#define IDC_TAB                         1101
#define IDC_SPIN_dez_S_x                1102
#define IDC_SPIN_kjx                    1102
#define IDC_SPIN_dez_K_x                1103
#define IDC_SPIN_tlgy                   1103
#define IDC_SPIN_tlgy_d                 1104
#define IDC_TAB2                        1104
#define IDC_SPIN_kjy                    1104
#define IDC_SPIN_tlgx_d                 1105
#define IDC_SPIN_kjx_d                  1105
#define IDC_SPIN_kjy_d                  1106
#define IDC_SPIN_sw_x                   1106
#define IDC_SPIN_sc                     1107
#define IDC_SPIN_scy                    1108
#define IDC_EDIT_compile                1108
#define IDC_SPIN_kw_x                   1108
#define IDC_SPIN_sw_y                   1108
#define IDC_SPIN_sc_d                   1109
#define IDC_EDIT_emf_file               1109
#define IDC_SPIN_sw_scx                 1109
#define IDC_SPIN_scy_d                  1110
#define IDC_BUTTON_P_fb                 1111
#define IDC_SPIN_shift_x                1111
#define IDC_BUTTON_K_fb                 1112
#define IDC_SPIN_sw_x2                  1112
#define IDC_SPIN_shift_y                1112
#define IDC_SPIN_sw_y2                  1113
#define IDC_SPIN_shift_x2               1113
#define IDC_COMBO_K_art                 1114
#define IDC_SPIN_shift_y2               1114
#define IDC_COMBO_P_art                 1115
#define IDC_EDIT_K_gr                   1116
#define IDC_EDIT_P_gr                   1117
#define IDC_SPIN_sw_Ayx                 1117
#define IDC_SPIN_K_gr                   1118
#define IDC_SPIN_sw_Ayy                 1118
#define IDC_SPIN_P_gr                   1119
#define IDC_SPIN_sw_Axx                 1119
#define IDC_SPIN_sw_Axy                 1120
#define IDC_BUTTON_hg_fb                1128
#define IDC_BUTTON_schr_x               1129
#define IDC_BUTTON_schr_y               1130
#define IDC_BUTTON_hg                   1133
#define IDC_CHECK2                      1134
#define IDC_CHECK_diff                  1134
#define IDC_CHECK3                      1135
#define IDC_COMBO_X_art                 1136
#define IDC_COMBO_Y_art                 1137
#define IDC_BUTTON_X_fb                 1138
#define IDC_BUTTON_Y_fb                 1139
#define IDC_EDIT_X_gr                   1140
#define IDC_EDIT_Y_gr                   1141
#define IDC_SPIN_X_gr                   1142
#define IDC_SPIN_Y_gr                   1143
#define IDC_SPIN_Ay                     1143
#define IDC_CHECK_ryx                   1144
#define IDC_EDIT_sgr_gr                 1144
#define IDC_SPIN_Ax_d                   1144
#define IDC_EDIT_Ygrid_gr               1144
#define IDC_CHECK_sxy                   1145
#define IDC_SPIN_sgr_gr                 1145
#define IDC_SPIN_Ay_d                   1145
#define IDC_SPIN_Ygrid_gr               1145
#define IDC_CHECK_s1yx                  1146
#define IDC_CHECK_sdg                   1146
#define IDC_EDIT_sgq_gr                 1146
#define IDC_SPIN_Vx                     1146
#define IDC_EDIT_Xgrid_gr               1146
#define IDC_CHECK_sryx                  1147
#define IDC_SPIN_sgq_gr                 1147
#define IDC_SPIN_Vy                     1147
#define IDC_SPIN_Xgrid_gr               1147
#define IDC_CHECK_xcrit                 1147
#define IDC_CHECK_sry                   1148
#define IDC_BUTTON_sgr_fb               1148
#define IDC_SPIN_Vx_d                   1148
#define IDC_BUTTON_Ygrid_fb             1148
#define IDC_CHECK_D                     1149
#define IDC_CHECK_ag3                   1149
#define IDC_COMBO_sgq_art               1149
#define IDC_SPIN_Vy_d                   1149
#define IDC_COMBO_Xgrid_art             1149
#define IDC_EDIT_CI                     1150
#define IDC_COMBO_sgr_art               1150
#define IDC_COMBO_Ygrid_art             1150
#define IDC_SPIN_CI                     1151
#define IDC_BUTTON_sgq_fb               1151
#define IDC_BUTTON_Xgrid_fb             1151
#define IDC_CHECK_rxy                   1152
#define IDC_CHECK_ag4                   1152
#define IDC_EDIT_sgr_gr2                1152
#define IDC_EDIT_ag4_gr                 1152
#define IDC_BUTTON_P                    1153
#define IDC_CHECK_sgam                  1153
#define IDC_SPIN_sgr_gr2                1153
#define IDC_SPIN_ag4_gr                 1153
#define IDC_BUTTON_SP                   1154
#define IDC_CHECK6                      1154
#define IDC_BUTTON_P1                   1154
#define IDC_EDIT_sg_R_gr                1154
#define IDC_CHECK_mtlg                  1154
#define IDC_CHECK_vx                    1155
#define IDC_EDIT_CI_t                   1155
#define IDC_SPIN_sg_R_gr                1155
#define IDC_CHECK_vy                    1156
#define IDC_SPIN_CI_t                   1156
#define IDC_EDIT_sgq_gr2                1156
#define IDC_EDIT_a4_gr                  1156
#define IDC_CHECK_t                     1156
#define IDC_EDIT_CI_z                   1157
#define IDC_CHECK_sga3                  1157
#define IDC_COMBO_sg_R_art              1157
#define IDC_SPIN_CI_z                   1158
#define IDC_CHECK_sga4                  1158
#define IDC_SPIN_sgq_gr2                1158
#define IDC_SPIN_a4_gr                  1158
#define IDC_EDIT_CI_t1                  1159
#define IDC_CHECK_log                   1159
#define IDC_BUTTON_sg_R_fb              1159
#define IDC_SPIN_CI_Fp_t                1160
#define IDC_BUTTON_sgr_fb2              1160
#define IDC_BUTTON_ag4_fb               1160
#define IDC_EDIT_CI_z1                  1161
#define IDC_COMBO_sgq_art2              1161
#define IDC_COMBO_a4_art                1161
#define IDC_SPIN_CI_Fp_z                1162
#define IDC_COMBO_sgr_art2              1162
#define IDC_COMBO_ag4_art               1162
#define IDC_BUTTON_SP1                  1163
#define IDC_BUTTON_sgq_fb2              1163
#define IDC_BUTTON_a4_fb                1163
#define IDC_CHECK_am                    1164
#define IDC_EDIT_sg_R_gr2               1164
#define IDC_EDIT_sa4g_gr                1164
#define IDC_CHECK_sd                    1165
#define IDC_SPIN_sg_R_gr2               1165
#define IDC_SPIN_sa4g_gr                1165
#define IDC_CHECK_a3                    1166
#define IDC_COMBO_sg_R_art2             1166
#define IDC_COMBO_sa4g_art              1166
#define IDC_CHECK_a4                    1167
#define IDC_BUTTON_sg_R_fb2             1167
#define IDC_BUTTON_sa4g_fb              1167
#define IDC_CHECK_fstream_rnd           1168
#define IDC_CHECK_splash                1169
#define IDC_CHECK_wnd_pos               1170
#define IDC_CHECK_csr                   1171
#define IDC_COMBO_r_art                 1172
#define IDC_BUTTON_r_fb                 1173
#define IDC_EDIT_r_gr                   1174
#define IDC_SPIN_r_gr                   1175
#define IDC_COMBO_sq_art                1176
#define IDC_BUTTON_sq_fb                1177
#define IDC_EDIT_sq_gr                  1178
#define IDC_SPIN_sq_gr                  1179
#define IDC_EDIT_sq_gr2                 1180
#define IDC_EDIT_Ax                     1180
#define IDC_EDIT_sa3g_gr                1180
#define IDC_SPIN_sq_gr2                 1181
#define IDC_EDIT_Ay                     1181
#define IDC_SPIN_sa3g_gr                1181
#define IDC_EDIT_r_gr2                  1182
#define IDC_EDIT_Vx                     1182
#define IDC_EDIT_ag3_gr                 1182
#define IDC_SPIN_r_gr2                  1183
#define IDC_EDIT_Vy                     1183
#define IDC_SPIN_ag3_gr                 1183
#define IDC_BUTTON_sq_fb2               1184
#define IDC_EDIT_Ax_d                   1184
#define IDC_BUTTON_sa3g_fb              1184
#define IDC_COMBO_r_art2                1185
#define IDC_EDIT_Ay_d                   1185
#define IDC_COMBO_ag3_art               1185
#define IDC_COMBO_sq_art2               1186
#define IDC_EDIT_Vx_d                   1186
#define IDC_COMBO_sa3g_art              1186
#define IDC_BUTTON_r_fb2                1187
#define IDC_EDIT_Vy_d                   1187
#define IDC_BUTTON_ag3_fb               1187
#define IDC_SPIN_Ax                     1188
#define IDC_BUTTON_Ax_reset             1189
#define IDC_COMBO1                      1190
#define IDC_COMBO_schema                1190
#define IDC_BUTTON1                     1191
#define IDC_SPIN_kw_y                   1192
#define IDC_BUTTON_By                   1192
#define IDC_SPIN_fw_xY                  1195
#define IDC_SPIN_fw_yY                  1196
#define IDC_SPIN_fw_xX                  1197
#define IDC_COMBO_sd_art                1197
#define IDC_SPIN_fw_yX                  1198
#define IDC_COMBO_sdg_art               1198
#define IDC_COMBO_sgx_art               1199
#define IDC_COMBO_a3_art                1200
#define IDC_BUTTON_sd_fb                1201
#define IDC_BUTTON_sdg_fb               1202
#define IDC_BUTTON_sgx_fb               1203
#define IDC_BUTTON_a3_fb                1204
#define IDC_EDIT_sd_gr                  1205
#define IDC_EDIT_sdg_gr                 1206
#define IDC_EDIT_sgx_gr                 1207
#define IDC_EDIT_a3_gr                  1208
#define IDC_SPIN_sd_gr                  1209
#define IDC_SPIN_sdg_gr                 1210
#define IDC_SPIN_sgx_gr                 1211
#define IDC_SPIN_a3_gr                  1212
#define IDC_COMBO_rxy_art               1213
#define IDC_COMBO_ryx_art               1214
#define IDC_COMBO_syx_art               1215
#define IDC_COMBO_sxy_art               1216
#define IDC_COMBO_s1yx_art              1217
#define IDC_COMBO_s1xy_art              1219
#define IDC_COMBO_srxy_art              1220
#define IDC_COMBO_sryx_art              1221
#define IDC_COMBO_srx_art               1222
#define IDC_COMBO_sry_art               1223
#define IDC_BUTTON_rxy_fb               1226
#define IDC_BUTTON_ryx_fb               1227
#define IDC_BUTTON_syx_fb               1228
#define IDC_BUTTON_sxy_fb               1229
#define IDC_BUTTON_s1yx_fb              1230
#define IDC_BUTTON_s1xy_fb              1231
#define IDC_BUTTON_srxy_fb              1232
#define IDC_BUTTON_sryx_fb              1233
#define IDC_BUTTON_srx_fb               1234
#define IDC_BUTTON_sry_fb               1235
#define IDC_EDIT_rxy_gr                 1236
#define IDC_SPIN_rxy_gr                 1237
#define IDC_EDIT_ryx_gr                 1238
#define IDC_SPIN_ryx_gr                 1239
#define IDC_EDIT_syx_gr                 1240
#define IDC_SPIN_syx_gr                 1241
#define IDC_EDIT_sxy_gr                 1242
#define IDC_SPIN_sxy_gr                 1243
#define IDC_EDIT_s1yx_gr                1244
#define IDC_SPIN_s1yx_gr                1245
#define IDC_EDIT_s1xy_gr                1246
#define IDC_SPIN_s1xy_gr                1247
#define IDC_EDIT_srxy_gr                1248
#define IDC_SPIN_srxy_gr                1249
#define IDC_EDIT_sryx_gr                1250
#define IDC_SPIN_sryx_gr                1251
#define IDC_EDIT_srx_gr                 1252
#define IDC_SPIN_srx_gr                 1253
#define IDC_EDIT_sry_gr                 1254
#define IDC_SPIN_sry_gr                 1255
#define IDC_CHECK_sgyx                  1256
#define IDC_CHECK_sgxy                  1257
#define IDC_SPIN_sw_scy                 1258
#define IDC_CHECK_p                     1259
#define IDC_CHECK_pa1                   1260
#define IDC_CHECK_pa2                   1261
#define IDC_CHECK_x0                    1262
#define IDC_CHECK_x1                    1263
#define IDC_CHECK_e                     1264
#define IDC_EDIT_df                     1266
#define IDC_CHECK_s0                    1267
#define IDC_CHECK_s1                    1268
#define IDC_CHECK_z                     1269
#define IDC_BUTTON_Bx                   1270
#define IDC_EDIT_Bx                     1271
#define IDC_COMBO_x0_art                1273
#define IDC_COMBO_s0_art                1274
#define IDC_COMBO_x1_art                1275
#define IDC_COMBO_s1_art                1276
#define IDC_COMBO_e_art                 1277
#define IDC_BUTTON_x0_fb                1278
#define IDC_BUTTON_s0_fb                1279
#define IDC_BUTTON_x1_fb                1280
#define IDC_BUTTON_s1_fb                1281
#define IDC_BUTTON_e_fb                 1282
#define IDC_EDIT_x0_gr                  1283
#define IDC_EDIT_s0_gr                  1284
#define IDC_EDIT_x1_gr                  1285
#define IDC_EDIT_s1_gr                  1286
#define IDC_EDIT_e_gr                   1287
#define IDC_SPIN_x0_gr                  1288
#define IDC_SPIN_s0_gr                  1289
#define IDC_SPIN_x1_gr                  1290
#define IDC_SPIN_s1_gr                  1291
#define IDC_SPIN_e_gr                   1292
#define IDC_SPIN_CI_Fe_t                1293
#define IDC_SPIN_CI_Fe_z                1294
#define IDC_EDIT_int_n                  1296
#define IDC_SPIN_int_n                  1297
#define IDC_EDIT_diff_n                 1298
#define IDC_SPIN_diff_n                 1299
#define IDC_CHECK_nwtn                  1300
#define IDC_CHECK_qspl                  1301
#define IDC_EDIT_mtlg_i                 1302
#define IDC_SPIN_mtlg_i                 1303
#define IDC_EDIT_THETA                  1308
#define IDC_EDIT_FXY                    1309
#define IDC_EDIT_LOG                    1310
#define ID_FUNKTIONSMATRIX_FFNEN        32771
#define ID_MODUS_FX                     32772
#define ID_MODUS_FP                     32773
#define ID_MODUS_RXY                    32774
#define ID_EINSTELLUNGEN_FARBEN         32775
#define ID_EINSTELLUNGEN_Parameter      32776
#define ID_FUNKTION_EMFSPEICHERN        32777
#define ID_FUNKTION_EMFFFNEN            32778
#define ID_MODUS_INV                    32782
#define ID_INFO                         32784
#define ID_EINSTELLUNGEN_Diagramm       32785
#define ID_EINSTELLUNGEN_Funktion       32786
#define ID_EINSTELLUNGEN_CURSOR_WEISS   32788
#define ID_EINSTELLUNGEN_CURSOR_SCHWARZ 32790
#define ID_EINSTELLUNGEN_APP            32791
#define ID_EINSTELLUNGEN_KOORDINATEN    32792
#define ID_MODUS_EPSILON                32793
#define ID_EINSTELLUNGEN_CURSOR_ACHSENVERSCHUB 32794
#define ID_EINSTELLUNGEN_CURSOR_VEKTORENVERSCHUB 32795
#define ID_FUNKTION_SPEICHERNUNTER      32796
#define ID_ANSICHT_FUNKTIONSMATRIXFXY   32803
#define ID_HILFE_HATTEICHKEINE          32804
#define ID_ANSICHT_THETAFENSTERQ        32805
#define ID_MODUS_FZX                    32806
#define ID_ANSICHT_GRP2LOG              32807
#define ID_FUNKTION_SPEICHERN           32808
#define ID_FUNKTION_EMFSPEICHERNUNTER   32809
#define ID_ANSICHT_STATUSLEISTE         32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1311
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
